name: auto-create-PR

on:
  push:
    branches:
      - 'release/*'

jobs:
  auto_merge:
    permissions: write-all
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
    - name: Crate from Release into main
      if: always()
      run: |
        BRANCH=$(echo "${{ github.ref }}" | sed 's@refs/heads/@@')
        PR_COUNT=$(gh pr list --state=open --base=main --head=${BRANCH} --limit 99999 | wc -l)
        echo "Number of PRs from ${BRANCH} to main: $PR_COUNT"
        if [ $PR_COUNT -gt 0 ]; then
          echo "There is at least one PR from ${BRANCH} to main."
        else
          echo "There are no PRs from ${BRANCH} to main."
          gh pr create --title "[AUTO]Merge changes from ${BRANCH} into main" --body "This PR was automatically created by GitHub Actions." --base main --head ${BRANCH}
          echo Created PR
        fi

    - name: Crate from Release into Release/NextRelease
      if: always()
      run: |

        BRANCH=$(echo "${{ github.ref }}" | sed 's@refs/heads/@@')
        target_version=$(echo "$BRANCH" | sed 's/release\///')

        echo "Branches newer than $target_version:"
        gh repo view AnotherBall/izumo-streaming-app --json refs --jq '.refs[] | select(.name | startswith("refs/heads/release/")) | .name | sub("refs/heads/"; "")' | while read -r branch; do
            branch_name=$(echo "$branch" | sed 's/origin\///')
            version=$(echo "$branch_name" | sed 's/release\///')
            
            version1=${version}
            version2=${target_version}
            IFS='.' read -ra v1_parts <<< "$version1"
            IFS='.' read -ra v2_parts <<< "$version2"

            echo "Check: ${version1} ${version2}"

            for i in {0..2}; do
              if ((v1_parts[$i] < v2_parts[$i])); then
                break
              fi
              if ((v1_parts[$i] > v2_parts[$i])); then
                echo "$version1 is higher than $version2"
                echo "$branch_name"
                  PR_COUNT=$(gh pr list --state=open --base=$branch_name --head=${BRANCH} --limit 99999 | wc -l)
                  echo "Number of PRs from ${BRANCH} to $branch_name: $PR_COUNT"
                  if [ $PR_COUNT -gt 0 ]; then
                    echo "There is at least one PR from ${BRANCH} to $branch_name."
                  else
                    echo "There are no PRs from ${BRANCH} to $branch_name."
                    gh pr create --title "[AUTO]Merge from ${BRANCH} into $branch_name" --body "This PR was automatically created by GitHub Actions." --base $branch_name --head ${BRANCH}
                    echo Created PR
                  fi
                break
              fi
            done
        done
  
