name: Rebase and Force Push PR

on:
  issue_comment:
    types: [created]

jobs:
  rebase_and_force_push:
    if: github.event_name == 'issue_comment' && contains(github.event.comment.html_url, '/pull/') && startsWith(github.event.comment.body, '/rebase --onto ')

    permissions:
      contents: write
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Rebase onto specified branch and force push
        run: |
          body="${{ github.event.comment.body }}"
          echo $body
          echo "Get Command"
          command=$(echo "${body}" | sed 's@/@@')
          echo $command

          echo "Get HeadBranch"
          headBranch=$(echo "${body}" | awk '{print $NF}')
          
          echo $headBranch
          
          echo "Fetch Start"
          git fetch origin
          echo "checkout Start"
          git checkout ${headBranch}
          echo "Rebase Start"
          git $command
          echo "Push Start"
          git push ${headBranch} --force

          