name: Rebase and Force Push PR

on:
  issue_comment:
    types: [created]

jobs:
  rebase_and_force_push:
    runs-on: ubuntu-latest
    steps:
      - name: Check if comment contains rebase onto command
        id: check
        run: |
          body=$(jq -r '.comment.body' "$GITHUB_EVENT_PATH")
          branchName=$(echo "$body" | grep -oP '/rebase onto by \K\S+')
          if [ -n "$branchName" ]; then
            git ls-remote origin "$branchName" >/dev/null 2>&1
            if [ $? -eq 0 ]; then
              echo "::set-output name=branchName::$branchName"
            else
              echo "Branch $branchName does not exist."
              exit 1
            fi
          fi

      - name: Checkout repository
        if: ${{ steps.check.outputs.branchName != '' }}
        uses: actions/checkout@v2

      - name: Rebase onto specified branch and force push
        if: ${{ steps.check.outputs.branchName != '' }}
        run: |
          git fetch origin
          git rebase --onto ${{ github.event.issue.pull_request.base.ref }} ${{ steps.check.outputs.branchName }} ${{ github.event.issue.pull_request.head.ref }}
          git push origin ${{ github.event.issue.pull_request.head.ref }} --force